[package]
name = "convertors"
version = "0.1.1"
authors = ["Viorel Bota <botaviorel@gmail.com>"]

[dependencies]
backend_declaration = { path = "../backend_declaration" }
command = { path = "../command" }
